services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    image: elixir-bot
    container_name: elixir-bot
    restart: unless-stopped
    working_dir: /app
    stdin_open: true
    tty: true
    volumes:
      - ./:/app
    networks:
      - discord-bot
  ollama:
    image: ollama/ollama:latest
    ports:
      - 11434:11434
    volumes:
      - .:/code
      - ./ollama/ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: always
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0
    networks:
      - discord-bot

networks:
  discord-bot:
    external: false
